name: Build and Deploy TurboRepo to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node & PNPM
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Create .env file
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > ./packages/db/.env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > ./apps/http-backend/.env
          echo "RABBITMQ_URL=${{ secrets.RABBITMQ_URL }}" >> ./apps/http-backend/.env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > ./apps/ws-backend/.env
          echo "RABBITMQ_URL=${{ secrets.RABBITMQ_URL }}" >> ./apps/ws-backend/.env

      - name: Generate Prisma Client
        run: pnpm --filter=./packages/db exec prisma generate

      - name: Build Turborepo
        run: pnpm build

      - name: Create Deployment Archive
        run: |
          #Copy Http-backend
          mkdir -p deploy/http-backend
          cp -r ./apps/http-backend/dist deploy/http-backend/dist
          cp ./apps/http-backend/.env deploy/http-backend

          #Copy WS-backend
          mkdir -p deploy/ws-backend
          cp -r ./apps/ws-backend/dist deploy/ws-backend/dist
          cp ./apps/ws-backend/.env deploy/ws-backend
          tar -czf build.tar.gz deploy

          #Copy Frontend
          mkdir -p deploy/frontend/standalone
          cp -r ./apps/frontend/.next/standalone deploy/frontend
          cp -r ./apps/frontend/public deploy/frontend/standalone/public
          cp -r ./apps/frontend/.next/static deploy/frontend/standalone/.next/static
          cp ./apps/frontend/package.json deploy/frontend/standalone

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

    # No need to manually write the key to ~/.ssh/id_rsa after this

      - name: Add Known Hosts
        run: ssh-keyscan ${{ secrets.DEPLOY_IP }} >> ~/.ssh/known_hosts

      - name: Upload Build to DEPLOY
        run: |
          scp build.tar.gz ${{ secrets.DEPLOY_USERNAME }}@${{ secrets.DEPLOY_IP }}:${{ secrets.DEPLOY_PATH }}

      - name: SSH and Deploy
        run: |
          ssh ${{ secrets.DEPLOY_USERNAME }}@${{ secrets.DEPLOY_IP }} << EOF
            set -e
            export PATH=\$PATH:/home/ubuntu/.nvm/versions/node/v22.14.0/bin
            mkdir -p ${{ secrets.DEPLOY_PATH }}
            cd ${{ secrets.DEPLOY_PATH }}

            # Clean old and unpack
            rm -rf deploy
            tar -xzf build.tar.gz

            #deploy
            cd deploy
            mv http-backend/dist/client/* http-backend/dist/
            mv ws-backend/dist/client/* ws-backend/dist/

            # Restart services
            cd http-backend
            pm2 delete http-backend || true
            pm2 start "node --env-file=.env dist/index.js" --name http-backend
            cd ..

            cd ws-backend
            pm2 delete ws-backend || true
            pm2 start "node --env-file=.env dist/index.js" --name ws-backend
            cd ..

            cd frontend/standalone
            pnpm install --prod --ignore-scripts
            pm2 delete frontend || true
            pm2 start "node server.js" --name frontend
            cd ..
          EOF
